/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/deliveries": {
    /** Returns a list of deliveries. */
    get: {
      parameters: {
        query: {
          offset: components["parameters"]["OffsetParam"];
          limit: components["parameters"]["LimitParam"];
          /**
           * @description Filter by driver name
           * @example Brown, Bob
           */
          driver?: string;
          /**
           * @description Filter by provider name
           * @example Amazon
           */
          provider?: string;
          /**
           * @description Filter by vehicle name
           * @example Honda Accord
           */
          vehicle?: string;
          /**
           * @description Filter by day
           * @example 1
           */
          day?: string;
          /**
           * @description Filter by month
           * @example 7
           */
          month?: string;
          /**
           * @description Filter by year
           * @example 2024
           */
          year?: string;
        };
      };
      responses: {
        /** @description A JSON array of user names */
        200: {
          content: {
            "application/json": {
              data: components["schemas"]["DeliveriesArray"];
              pagination: components["schemas"]["Pagination"];
            };
          };
        };
        /** @description Bad request - validation error */
        400: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
    /** Creates a new delivery. */
    post: {
      /** @description Delivery object to be added to the list */
      requestBody: {
        content: {
          "application/json": components["schemas"]["DeliveryCreate"];
        };
      };
      responses: {
        /** @description Delivery created */
        201: {
          content: {
            "application/json": components["schemas"]["MessageResponse"];
          };
        };
        /** @description Bad request - validation error */
        400: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/deliveries/{id}": {
    /** Returns a delivery by id. */
    get: {
      parameters: {
        path: {
          /** @description The id of the delivery to retrieve */
          id: string;
        };
      };
      responses: {
        /** @description A JSON array of user names */
        200: {
          content: {
            "application/json": components["schemas"]["Delivery"];
          };
        };
        /** @description Bad request - validation error */
        400: {
          content: never;
        };
        /** @description Delivery not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
    /** Updates a delivery by id. */
    put: {
      parameters: {
        path: {
          /** @description The id of the delivery to update */
          id: string;
        };
      };
      /** @description Delivery object to be updated */
      requestBody: {
        content: {
          "application/json": components["schemas"]["DeliveryCreate"];
        };
      };
      responses: {
        /** @description Delivery updated */
        200: {
          content: {
            "application/json": components["schemas"]["MessageResponse"];
          };
        };
        /** @description Bad request - validation error */
        400: {
          content: never;
        };
        /** @description Delivery not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
    /** Deletes a delivery by id. */
    delete: {
      parameters: {
        path: {
          /** @description The id of the delivery to delete */
          id: string;
        };
      };
      responses: {
        /** @description Delivery deleted */
        200: {
          content: {
            "application/json": components["schemas"]["MessageResponse"];
          };
        };
        /** @description Bad request - validation error */
        400: {
          content: never;
        };
        /** @description Delivery not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/clients": {
    /** Returns a list of clients. */
    get: {
      parameters: {
        query: {
          offset: components["parameters"]["OffsetParam"];
          limit: components["parameters"]["LimitParam"];
          /**
           * @description Filter by client active status
           * @example ACTIVE
           */
          status?: components["schemas"]["ActiveStatus"];
          /**
           * @description Filter by client name
           * @example Amazon
           */
          name?: string;
          /**
           * @description Filter by city name
           * @example Paris
           */
          city?: string;
          /**
           * @description Filter by postal code
           * @example 75008
           */
          postalCode?: string;
          /**
           * @description Filter by country
           * @example France
           */
          country?: string;
        };
      };
      responses: {
        /** @description A JSON array of user names */
        200: {
          content: {
            "application/json": {
              data: components["schemas"]["ClientsArray"];
              pagination: components["schemas"]["Pagination"];
            };
          };
        };
        /** @description Bad request - validation error */
        400: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
    /** Creates a new client. */
    post: {
      /** @description Client object to be added to the list */
      requestBody: {
        content: {
          "application/json": components["schemas"]["ClientCreate"];
        };
      };
      responses: {
        /** @description Client created */
        201: {
          content: {
            "application/json": components["schemas"]["MessageResponse"];
          };
        };
        /** @description Bad request - validation error */
        400: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
  "/clients/{id}": {
    /** Returns a client by id. */
    get: {
      parameters: {
        path: {
          /** @description The id of the client to retrieve */
          id: string;
        };
      };
      responses: {
        /** @description A JSON array of user names */
        200: {
          content: {
            "application/json": components["schemas"]["Client"];
          };
        };
        /** @description Bad request - validation error */
        400: {
          content: never;
        };
        /** @description Client not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
    /** Updates a client by id. */
    put: {
      parameters: {
        path: {
          /** @description The id of the client to update */
          id: string;
        };
      };
      /** @description Client object to be updated */
      requestBody: {
        content: {
          "application/json": components["schemas"]["ClientCreate"];
        };
      };
      responses: {
        /** @description Client updated */
        200: {
          content: {
            "application/json": components["schemas"]["MessageResponse"];
          };
        };
        /** @description Bad request - validation error */
        400: {
          content: never;
        };
        /** @description Client not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
    /** Deletes a client by id. */
    delete: {
      parameters: {
        path: {
          /** @description The id of the client to delete */
          id: string;
        };
      };
      responses: {
        /** @description Client deleted */
        200: {
          content: {
            "application/json": components["schemas"]["MessageResponse"];
          };
        };
        /** @description Bad request - validation error */
        400: {
          content: never;
        };
        /** @description Client not found */
        404: {
          content: never;
        };
        /** @description Internal server error */
        500: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    MessageResponse: {
      /** @example Success */
      message?: string;
    };
    Pagination: {
      /** @example 1 */
      currentPage?: number;
      /** @example 7 */
      totalPages?: number;
      /** @example true */
      hasNextPage?: boolean;
      /** @example false */
      hasPreviousPage?: boolean;
      /** @example 89 */
      totalItems?: number;
    };
    /**
     * @description The type of the entity (in UPPERCASE)
     * @enum {string}
     */
    PickupEntities: "CLIENT" | "RELAY";
    /**
     * @description The active status of the entity (in UPPERCASE)
     * @enum {string}
     */
    ActiveStatus: "ACTIVE" | "INACTIVE";
    Delivery: {
      /**
       * @description The id of the delivery
       * @example 1
       */
      id: number;
      /**
       * @description The name of the driver (Lastname, Firstname)
       * @example Smith, John
       */
      driver: string;
      /**
       * @description The name of the vehicle (Brand Model)
       * @example Ford Transit
       */
      vehicle: string;
      /**
       * @description The name of the company that provided the delivery
       * @example Amazon
       */
      provider: string;
      /**
       * @description The price of the hotel, in euros
       * @example 100
       */
      hotelPrice: number;
      /**
       * @description The name of the company that outsourced the delivery
       * @example Google
       */
      outsourcedTo: string;
      /**
       * @description Array of pickups
       * @example [
       *   {
       *     "date": "2021-07-01",
       *     "infos": {
       *       "id": 1,
       *       "name": "Amazon",
       *       "streetNumber": 123,
       *       "street": "Main St",
       *       "city": "Paris",
       *       "postalCode": 75008,
       *       "country": "France",
       *       "comment": "Derrière le hangar",
       *       "active": true,
       *       "type": "CLIENT"
       *     }
       *   }
       * ]
       */
      pickups: components["schemas"]["Pickup"][];
      /**
       * @description Array of dropoffs
       * @example [
       *   {
       *     "date": "2021-07-01",
       *     "infos": {
       *       "id": 1,
       *       "name": "Amazon",
       *       "streetNumber": 123,
       *       "street": "Main St",
       *       "city": "Paris",
       *       "postalCode": 75008,
       *       "country": "France",
       *       "comment": "Derrière le hangar",
       *       "active": true,
       *       "type": "CLIENT"
       *     }
       *   }
       * ]
       */
      dropoffs: components["schemas"]["Pickup"][];
      /**
       * @description The id of the company that does the delivery
       * @example 1
       */
      companyId: number;
    };
    DeliveryCreate: {
      /**
       * @description The id of the driver that does the delivery
       * @example 1
       */
      driverId: number;
      /**
       * @description The id of the vehicle that does the delivery
       * @example 1
       */
      vehicleId: number;
      /**
       * @description The id of the company that provided the delivery
       * @example 1
       */
      providerId: number;
      /**
       * @description The price of the hotel, in euros
       * @example 100
       */
      hotelPrice?: number;
      /**
       * @description Array of pickups
       * @example [
       *   {
       *     "date": "2021-07-01",
       *     "entityId": 1,
       *     "entityType": "CLIENT"
       *   }
       * ]
       */
      pickups: components["schemas"]["PickupCreate"][];
      /**
       * @description Array of dropoffs
       * @example [
       *   {
       *     "date": "2021-07-01",
       *     "entityId": 1,
       *     "entityType": "CLIENT"
       *   }
       * ]
       */
      dropoffs: components["schemas"]["PickupCreate"][];
      /**
       * @description The id of the company that outsourced the delivery
       * @example 2
       */
      outsourcedTo?: number;
    };
    DeliveriesArray: components["schemas"]["Delivery"][];
    Pickup: {
      /** @example 2021-07-01 */
      date: string;
      infos: {
        /** @example 1 */
        id?: number;
        /** @example Amazon */
        name?: string;
        /** @example 123 */
        streetNumber?: number;
        /** @example Main St */
        street?: string;
        /** @example Paris */
        city?: string;
        /** @example 75008 */
        postalCode?: string;
        /** @example France */
        country?: string;
        /** @example Derrière le hangar */
        comment?: string;
        /** @example true */
        active?: boolean;
        /**
         * @description The type of the entity (in UPPERCASE)
         * @example CLIENT
         */
        type?: string;
      };
    };
    PickupCreate: {
      /** @example 2021-07-01 */
      date?: string;
      /** @example 1 */
      entityId?: number;
      entityType?: components["schemas"]["PickupEntities"];
    };
    Client: {
      /**
       * @description The id of the client
       * @example 1
       */
      id: number;
      /**
       * @description The name of the client
       * @example Amazon
       */
      name: string;
      /**
       * @description The street number of the client
       * @example 123
       */
      streetNumber: string;
      /**
       * @description The street of the client
       * @example Main St
       */
      street: string;
      /**
       * @description The city of the client
       * @example Paris
       */
      city: string;
      /**
       * @description The postal code of the client
       * @example 75008
       */
      postalCode: string;
      /**
       * @description The country of the client
       * @example France
       */
      country: string;
      /**
       * @description The comment of the client
       * @example Derrière le hangar
       */
      comment?: string;
      /**
       * @description The active status of the client
       * @example true
       */
      active: boolean;
      /**
       * @description The phone number of the client
       * @example 33612345678
       */
      phone: string;
      /**
       * @description The email of the client
       * @example example@mail.com
       */
      email: string;
    };
    ClientsArray: components["schemas"]["Client"][];
    ClientCreate: {
      /**
       * @description The name of the client
       * @example Amazon
       */
      name: string;
      /**
       * @description The street number of the client
       * @example 123
       */
      streetNumber?: string;
      /**
       * @description The street of the client
       * @example Main St
       */
      street: string;
      /**
       * @description The city of the client
       * @example Paris
       */
      city: string;
      /**
       * @description The postal code of the client
       * @example 75008
       */
      postalCode?: string;
      /**
       * @description The country of the client
       * @example France
       */
      country: string;
      /**
       * @description The comment of the client
       * @example Derrière le hangar
       */
      comment?: string;
      /**
       * @description The active status of the client
       * @example true
       */
      active: boolean;
      /**
       * @description The phone number of the client
       * @example 33612345678
       */
      phone?: string;
      /**
       * @description The email of the client
       * @example example@mail.com
       */
      email?: string;
    };
  };
  responses: never;
  parameters: {
    /** @description Number of items to skip */
    OffsetParam: string;
    /** @description Number of items to return */
    LimitParam: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
